### PR TITLE
slight changes to support changes in dropwizard 1.0

### PR DESCRIPTION
**Pull request by garyschulte**
changes to support dropwizard 1.0+

### CODE REVIEW

**Comment by zapodot** [comment]
Looks like you broke the buld. I guess it's because DW 1.0 is based on Java8. I will change build settings and try again

**Comment by zapodot** [comment]
Changed build settings for Travis. Should build now

**Comment by garyschulte** [comment]
Thx - I didn't see a way to change or suggest travis settings via PR.

**Comment by zapodot** [comment]
This change has now been to released to Maven central as part of v. 1.1. Thx @garyschulte for your contribution 👍

**Pull request merged**
